name: Prettier

on: push

jobs:
  prettier_action:
    name: Prettier Action

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prettify code
        uses: creyD/prettier_action@v3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
